# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DeepZoom Blog
subtitle: "Trips on the water"
email: jay@deepzoom.com
description: >- # this means to ignore newlines until "baseurl:"
  DeepZoom helps you plan trips on the water.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://blog.deepzoom.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: "jaybo/deepzoom-blog"
logo: "/assets/images/arrow48x48.png"

twitter_username: jayborseth
github_username:  jaybo
minimal_mistakes_skin: contrast
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jay Borseth"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "DeepZoom releases, trips, and features."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:jay@deepzoom.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.deepzoom.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jayborseth"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jaybo"



footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jayborseth"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jaybo"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      words_per_minute: 75
      comments: false
      share: true
      related: true
      show_date: true
      classes: wide
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

facebook:
  app_id: 28191254059

twitter:
  username: "jayborseth"
